# Sets `last_modified_at` on every page from git history so sitemap.xml can
# report an honest <lastmod>. A page counts as modified when the last commit
# touched any file it is rendered from. Uncommitted edits are ignored, and a
# page is left without a date when git is unavailable (for example in a shallow
# clone), in which case the sitemap simply omits <lastmod>.

require "open3"
require "time"

module LastModified
  # Most pages are rendered from shared data and templates as well as their
  # own source file.
  SHARED = %w[_data _includes _layouts].freeze

  # Paper pages are generated by jekyll-scholar from the bibliography.
  PAPER = %w[_bibliography _data/paper_details.yml _layouts/paper.html _layouts/default.html _includes].freeze

  def self.commit_time(site, paths)
    paths = paths.select { |path| File.exist?(File.join(site.source, path)) }
    return nil if paths.empty?

    out, status = Open3.capture2("git", "-C", site.source, "log", "-1", "--format=%cI", "--", *paths)
    return nil unless status.success? && !out.strip.empty?

    Time.iso8601(out.strip)
  rescue StandardError
    nil
  end
end

Jekyll::Hooks.register :site, :pre_render do |site|
  site.pages.each do |page|
    next unless page.output_ext == ".html"

    entry = page.data["entry"]
    paths =
      if entry
        key = entry["key"]
        LastModified::PAPER + ["papers/#{key}.pdf", "slides/#{key}.pdf"]
      else
        LastModified::SHARED + [page.relative_path]
      end

    time = LastModified.commit_time(site, paths)
    page.data["last_modified_at"] = time if time
  end
end
