#!/usr/bin/env ruby
# frozen_string_literal: true

# Fills in missing _data/paper_details.yml records from public metadata APIs.
#
# Detail pages at /papers/<key>/ are generated by jekyll-scholar straight from
# _bibliography/papers.bib and render fine without a details record. This script
# only supplies the optional enrichment -- abstract, DOI, publisher URL -- for
# bib keys that have no record yet.
#
# Sources, in the order they are consulted:
#
#   1. Semantic Scholar, via the author feed in _data/profile.yml, so titles are
#      matched against this author's own papers rather than a global index.
#   2. Crossref, to resolve a DOI when Semantic Scholar has no record.
#   3. OpenAlex, which reconstructs abstracts for many records where the
#      publisher never deposited one (IEEE in particular deposits no abstracts
#      to Crossref, and Semantic Scholar is often empty for brand-new issues).
#
# Rules it holds to:
#
#   * Curated records are never touched. Only blocks carrying the AUTO_MARKER
#     comment are rewritten; delete that comment line to freeze an entry and the
#     script will leave it alone forever after.
#   * Never fatal. Any network or parse failure is reported and skipped; the
#     script still exits 0 so a CI deploy is never blocked by a third-party API.
#   * Code URLs are left alone. They span several GitHub orgs and the repo names
#     do not track bib keys (promptcache -> prompt-cache, cord -> CORD), so
#     guessing them would be wrong often enough to be worse than leaving blank.
#
# Usage: ruby scripts/fetch_paper_details.rb [--dry-run] [--verbose]

require "json"
require "net/http"
require "uri"
require "yaml"

ROOT = File.expand_path("..", __dir__)
BIB_PATH = File.join(ROOT, "_bibliography", "papers.bib")
DETAILS_PATH = File.join(ROOT, "_data", "paper_details.yml")
PROFILE_PATH = File.join(ROOT, "_data", "profile.yml")

DRY_RUN = ARGV.include?("--dry-run")
VERBOSE = ARGV.include?("--verbose")

AUTO_MARKER = "# Auto-filled by scripts/fetch_paper_details.rb"

# Dice coefficient over word tokens; 1.0 is an exact match after normalisation.
TITLE_MATCH_THRESHOLD = 0.82

# ---------------------------------------------------------------- bibtex ----

# Reads one field value, honouring nested braces so `title = {{A: B}}` yields
# `{A: B}` rather than stopping at the first closing brace.
def read_braced_value(text, open_index)
  depth = 0
  index = open_index
  while index < text.length
    depth += 1 if text[index] == "{"
    depth -= 1 if text[index] == "}"
    return [text[(open_index + 1)...index], index + 1] if depth.zero?

    index += 1
  end
  [text[(open_index + 1)..] || "", text.length]
end

def parse_fields(body)
  fields = {}
  cursor = 0
  while (match = body.match(/([A-Za-z]+)\s*=\s*/, cursor))
    name = match[1].downcase
    value_start = match.end(0)
    if body[value_start] == "{"
      value, cursor = read_braced_value(body, value_start)
    else
      stop = body.index(/[,\n]/, value_start) || body.length
      value = body[value_start...stop]
      cursor = stop + 1
    end
    fields[name] = value.to_s.strip
  end
  fields
end

def parse_bib(path)
  text = File.read(path)
  entries = []
  text.scan(/@([A-Za-z]+)\s*\{\s*([^,\s]+)\s*,/) do
    key = Regexp.last_match(2)
    body_start = Regexp.last_match.end(0)
    depth = 1
    index = body_start
    while index < text.length && depth.positive?
      depth += 1 if text[index] == "{"
      depth -= 1 if text[index] == "}"
      index += 1
    end
    entries << { key: key, fields: parse_fields(text[body_start...(index - 1)]) }
  end
  entries
end

def clean_title(raw)
  raw.to_s.gsub(/[{}]/, "").gsub(/\s+/, " ").strip
end

# ------------------------------------------------------------- matching ----

def normalise(title)
  title.downcase.gsub(/[^a-z0-9]+/, " ").split.join(" ")
end

def similarity(left, right)
  a = normalise(left).split
  b = normalise(right).split
  return 0.0 if a.empty? || b.empty?
  return 1.0 if a == b

  overlap = (a & b).sum { |word| [a.count(word), b.count(word)].min }
  (2.0 * overlap) / (a.length + b.length)
end

# ------------------------------------------------------------------ http ----

def contact_email
  YAML.safe_load_file(PROFILE_PATH)["email"]
rescue StandardError
  nil
end

USER_AGENT = begin
  mail = contact_email
  base = "anuragkhandelwal.com-metadata-fetcher/1.0"
  mail ? "#{base} (mailto:#{mail})" : base
end

def get_json(url, attempts: 3)
  attempts.times do |attempt|
    begin
      uri = URI(url)
      response = Net::HTTP.start(uri.host, uri.port, use_ssl: true,
                                 open_timeout: 10, read_timeout: 25) do |http|
        http.get(uri.request_uri,
                 "User-Agent" => USER_AGENT,
                 "Accept" => "application/json")
      end

      return JSON.parse(response.body) if response.code == "200"
      return nil if response.code == "404"

      # Semantic Scholar rate-limits anonymous callers; back off and retry.
      if response.code == "429" || response.code.start_with?("5")
        warn "    retrying after HTTP #{response.code}" if VERBOSE
        sleep(2**attempt)
        next
      end

      warn "    HTTP #{response.code} from #{uri.host}" if VERBOSE
      return nil
    rescue StandardError => error
      warn "    request failed (#{error.class}): #{error.message}" if VERBOSE
      sleep(2**attempt)
    end
  end
  nil
end

# -------------------------------------------------------------- sources ----

def semantic_scholar_author_id
  YAML.safe_load_file(PROFILE_PATH)["semantic_scholar"].to_s[%r{/author/(\d+)}, 1]
rescue StandardError
  nil
end

def semantic_scholar_papers
  author_id = semantic_scholar_author_id
  return [] unless author_id

  url = "https://api.semanticscholar.org/graph/v1/author/#{author_id}/papers" \
        "?fields=title,abstract,externalIds,year,venue&limit=500"
  payload = get_json(url)
  payload.is_a?(Hash) ? Array(payload["data"]).compact : []
end

# Crossref abstracts arrive as JATS XML fragments.
def strip_jats(text)
  return nil if text.nil?

  cleaned = text.gsub(%r{<[^>]+>}, " ").gsub(/\s+/, " ").strip.sub(/\AAbstract\s*/i, "")
  cleaned.empty? ? nil : cleaned
end

def crossref_lookup(title)
  query = URI.encode_www_form_component(title)
  payload = get_json("https://api.crossref.org/works?query.bibliographic=#{query}&rows=5")
  return nil unless payload.is_a?(Hash)

  Array(payload.dig("message", "items")).each do |item|
    candidate = Array(item["title"]).first
    next if candidate.nil?
    next if similarity(title, candidate) < TITLE_MATCH_THRESHOLD

    return { doi: item["DOI"], abstract: strip_jats(item["abstract"]) }
  end
  nil
end

# OpenAlex stores abstracts as a word -> [positions] map rather than plain text.
def reconstruct_inverted_abstract(index)
  return nil unless index.is_a?(Hash) && !index.empty?

  positions = {}
  index.each do |word, spots|
    Array(spots).each { |spot| positions[spot] = word }
  end
  return nil if positions.empty?

  text = positions.keys.sort.map { |slot| positions[slot] }.join(" ")
  text = text.gsub(/\s+/, " ").strip
  text.empty? ? nil : text
end

def openalex_lookup(doi: nil, title: nil)
  work = nil

  if doi
    work = get_json("https://api.openalex.org/works/doi:#{doi}")
    work = nil unless work.is_a?(Hash) && work["id"]
  end

  if work.nil? && title
    query = URI.encode_www_form_component(title)
    payload = get_json("https://api.openalex.org/works?filter=title.search:#{query}&per-page=5")
    Array(payload.is_a?(Hash) ? payload["results"] : nil).each do |candidate|
      next if candidate["title"].nil?
      next if similarity(title, candidate["title"]) < TITLE_MATCH_THRESHOLD

      work = candidate
      break
    end
  end

  return nil unless work

  {
    doi: work["doi"].to_s.sub(%r{\Ahttps?://doi\.org/}, "").then { |d| d.empty? ? nil : d },
    abstract: reconstruct_inverted_abstract(work["abstract_inverted_index"])
  }
end

# ------------------------------------------------------------ yaml output ----

def folded_block(text, indent: 4, width: 76)
  lines = []
  current = +""
  text.split(/\s+/).each do |word|
    if current.empty?
      current = +word
    elsif current.length + 1 + word.length <= width
      current << " " << word
    else
      lines << current
      current = +word
    end
  end
  lines << current unless current.empty?
  lines.map { |line| "#{" " * indent}#{line}" }.join("\n")
end

def render_entry(key, data)
  body = +""
  body << %(  doi: "#{data[:doi]}"\n) if data[:doi]
  body << %(  official_url: "#{data[:official_url]}"\n) if data[:official_url]
  if data[:abstract]
    body << "  abstract: >-\n"
    body << folded_block(data[:abstract]) << "\n"
  end
  return nil if body.empty?

  "\n#{AUTO_MARKER} from #{data[:source]}.\n" \
    "# Review the wording; delete these two comment lines to freeze this entry.\n" \
    "#{key}:\n#{body}"
end

# Splits the file into the text that must survive untouched and the auto-filled
# blocks, which may be regenerated. A block runs from its marker comment through
# the last indented line of its mapping.
def extract_auto_blocks(text)
  lines = text.lines
  kept = []
  auto = {}
  index = 0

  while index < lines.length
    unless lines[index].start_with?(AUTO_MARKER)
      kept << lines[index]
      index += 1
      next
    end

    cursor = index + 1
    cursor += 1 while cursor < lines.length && lines[cursor].start_with?("#")
    match = cursor < lines.length ? lines[cursor].match(/\A([A-Za-z0-9_-]+):\s*$/) : nil

    unless match
      kept << lines[index]
      index += 1
      next
    end

    body_start = cursor + 1
    body_end = body_start
    while body_end < lines.length &&
          (lines[body_end].strip.empty? || lines[body_end].start_with?(" ", "\t"))
      break if lines[body_end].strip.empty? &&
               (body_end + 1 >= lines.length || !lines[body_end + 1].start_with?(" ", "\t"))

      body_end += 1
    end

    # Keep the original comment lines so a retained block keeps its provenance
    # and re-running the script does not churn the file.
    auto[match[1]] = {
      comments: lines[index...cursor].join,
      body: lines[body_start...body_end].join
    }
    kept.pop while kept.last && kept.last.strip.empty?
    index = body_end
  end

  [kept.join.sub(/\n*\z/, "\n"), auto]
end

# ------------------------------------------------------------------ main ----

entries = parse_bib(BIB_PATH)
original_text = File.read(DETAILS_PATH)
curated_text, auto_blocks = extract_auto_blocks(original_text)
details = YAML.safe_load_file(DETAILS_PATH) || {}

# Resolve anything with no record at all, plus any auto-filled record that is
# still missing an abstract or DOI -- a later deposit may have filled the gap.
targets = entries.select do |entry|
  record = details[entry[:key]]
  if record.nil?
    true
  elsif auto_blocks.key?(entry[:key])
    record["abstract"].nil? || record["doi"].nil?
  else
    false
  end
end

if targets.empty?
  puts "Nothing to resolve: #{entries.length} bib entries, " \
       "#{auto_blocks.length} auto-filled record(s), all complete."
  exit 0
end

new_keys = targets.reject { |entry| details.key?(entry[:key]) }.map { |entry| entry[:key] }
refresh_keys = targets.map { |entry| entry[:key] } - new_keys
puts "Bib entries: #{entries.length}."
puts "  new:     #{new_keys.empty? ? "none" : new_keys.join(", ")}"
puts "  refresh: #{refresh_keys.empty? ? "none" : refresh_keys.join(", ")}"

catalogue = semantic_scholar_papers
if catalogue.empty?
  warn "Semantic Scholar returned nothing; relying on Crossref and OpenAlex."
else
  puts "Semantic Scholar returned #{catalogue.length} authored papers."
end

resolved = {}
unresolved = []

targets.each do |entry|
  title = clean_title(entry[:fields]["title"])
  puts "\n- #{entry[:key]}: #{title}"

  found = {}
  sources = []

  best = catalogue.max_by { |paper| similarity(title, paper["title"].to_s) }
  score = best ? similarity(title, best["title"].to_s) : 0.0
  if best && score >= TITLE_MATCH_THRESHOLD
    puts "    Semantic Scholar matched (#{(score * 100).round}%)"
    found[:abstract] = best["abstract"] if best["abstract"]
    found[:doi] = best.dig("externalIds", "DOI")
    sources << "Semantic Scholar" if found[:abstract] || found[:doi]
  elsif VERBOSE && best
    puts "    best Semantic Scholar candidate only #{(score * 100).round}%"
  end

  if found[:doi].nil? && (crossref = crossref_lookup(title))
    puts "    Crossref supplied a DOI"
    found[:doi] = crossref[:doi]
    found[:abstract] ||= crossref[:abstract]
    sources << "Crossref"
  end

  # OpenAlex last: it is the most reliable abstract source for publishers that
  # deposit none, which is why an IEEE record can reach this point bare.
  if found[:abstract].nil?
    openalex = openalex_lookup(doi: found[:doi], title: title)
    if openalex && openalex[:abstract]
      puts "    OpenAlex supplied the abstract"
      found[:abstract] = openalex[:abstract]
      found[:doi] ||= openalex[:doi]
      sources << "OpenAlex"
    elsif VERBOSE
      puts "    OpenAlex had no abstract either"
    end
  end

  found[:official_url] = "https://doi.org/#{found[:doi]}" if found[:doi]
  found.compact!

  if found.empty?
    puts "    no metadata found -- add this one by hand"
    unresolved << entry[:key]
  else
    found[:source] = sources.uniq.join(" and ")
    puts "    fields: #{(found.keys - [:source]).join(", ")}"
    resolved[entry[:key]] = found
  end
end

# Keep any previously auto-filled block we could not improve on this run.
rendered = []
auto_blocks.each_key do |key|
  next if resolved.key?(key)

  rendered << "\n#{auto_blocks[key][:comments]}#{key}:\n#{auto_blocks[key][:body]}"
end
resolved.each { |key, data| rendered << render_entry(key, data) }

output = curated_text + rendered.compact.join

puts "\n#{"=" * 68}"
if output == original_text
  puts "No change."
elsif DRY_RUN
  puts "--dry-run; would write:\n\n#{rendered.compact.join}"
else
  File.write(DETAILS_PATH, output)
  puts "Wrote _data/paper_details.yml:"
  resolved.each { |key, data| puts "  #{key} (#{(data.keys - [:source]).join(", ")}) <- #{data[:source]}" }
end

puts "\nStill needs a hand-written record: #{unresolved.join(", ")}" unless unresolved.empty?
puts "Code URLs are never auto-filled; add them manually when a repo exists."

exit 0
