#!/usr/bin/env ruby

require "fileutils"
require "yaml"

ROOT = File.expand_path("..", __dir__)
DATA = File.join(ROOT, "_data")
OUTPUT = File.join(ROOT, "cv", "generated")

def load_data(name)
  YAML.safe_load_file(File.join(DATA, "#{name}.yml"), aliases: true)
end

def tex(value)
  replacements = {
    "\\" => "\\textbackslash{}",
    "&" => "\\&",
    "%" => "\\%",
    "$" => "\\$",
    "#" => "\\#",
    "_" => "\\_",
    "{" => "\\{",
    "}" => "\\}"
  }
  value.to_s.gsub(/[\\&%$#_{}]/) { |character| replacements.fetch(character) }
end

def tex_period(value)
  tex(value).gsub("-", "$-$")
end

def period(person)
  return person["period"] if person["period"]
  return nil unless person["start"] || person["end"]

  "#{person['start']}-#{person['end']}".sub(/-\z/, "-")
end

def markdown_to_tex(value)
  result = +""
  cursor = 0
  value.to_enum(:scan, /\[([^\]]+)\]\(([^)]+)\)/).each do
    match = Regexp.last_match
    result << tex(value[cursor...match.begin(0)])
    result << "\\href{#{match[2]}}{#{tex(match[1])}}"
    cursor = match.end(0)
  end
  result << tex(value[cursor..])
  result
end

def write_section(name, lines)
  File.write(
    File.join(OUTPUT, "#{name}.tex"),
    (["% Generated by scripts/generate_cv.rb. Do not edit."] + lines).join("\n") + "\n"
  )
end

profile = load_data("profile")
education = load_data("education")
work_history = load_data("work_history")
awards = load_data("awards_honors")
research_focus = load_data("research_focus")
research_impact = load_data("research_impact")
invited_talks = load_data("invited_talks")
funding = load_data("funding")
teaching = load_data("teaching")
advising = load_data("advising")
education_outreach = load_data("education_outreach")
community_service = load_data("community_service")
university_service = load_data("university_service")
department_service = load_data("department_service")

FileUtils.mkdir_p(OUTPUT)
Dir.glob(File.join(OUTPUT, "*.tex")).each { |path| FileUtils.rm_f(path) }

File.write(File.join(OUTPUT, "profile.tex"), <<~TEX)
  % Generated by scripts/generate_cv.rb. Do not edit.
  \\newcommand{\\cvname}{#{tex(profile['name'])}}
  \\newcommand{\\cvtitle}{#{tex(profile['title'])}}
  \\newcommand{\\cvinstitution}{#{tex(profile['institution'])}}
  \\newcommand{\\cvemail}{#{tex(profile['email'])}}
  \\newcommand{\\cvwebsite}{#{profile['website']}}
TEX

education_lines = []
education.each_with_index do |entry, index|
  label = index.zero? ? " \\Large{Education}    &" : "     &"
  education_lines << "#{label} \\textbf{#{tex(entry['institution'])}} \\\\#{index.zero? ? '\\vspace{0.5em}' : ''}"
  details = "\\textit{#{tex(entry['degree'])} (#{entry['start']} $-$ #{entry['end']})}"
  details += ", \\textit{Advised by #{tex(entry['advisor'])}}" if entry["advisor"]
  education_lines << "     & \\quad\\enskip #{details} \\\\"
end
education_lines << "     & \\\\"
write_section("education", education_lines)

work_lines = []
work_history.each_with_index do |entry, index|
  first = index.zero?
  label = first ? " \\Large{Work}     &" : "     &"
  work_lines << "#{label} \\textbf{#{tex(entry['institution'])}#{entry['unit'] ? ", #{tex(entry['unit'])}" : ''}}\\\\#{index == 1 ? '\\vspace{0.5em}' : ''}"
  entry["positions"].each_with_index do |position, position_index|
    role_label = first && position_index.zero? ? " \\Large{History}  &" : "     &"
    range = position["period"] || "#{position['start']} - #{position['end']}"
    suffix = first && position_index.zero? ? "\\vspace{0.5em}" : ""
    work_lines << "#{role_label} \\quad\\enskip \\textit{#{tex(position['title'])}, #{tex(range)}}\\\\#{suffix}"
  end
end
work_lines << "     & \\\\"
write_section("work_history", work_lines)

award_lines = []
awards.each_with_index do |award, index|
  label = index.zero? ? " \\Large{Awards \\&} &" : "     &"
  award_lines << "#{label} \\textbf{#{tex(award['name'])}}\\\\"
  detail_label = index.zero? ? " \\Large{Honors} &" : "     &"
  detail = []
  detail << tex(award["description"]) if award["description"]
  detail << "\\emph{#{tex(award['work'])}}" if award["work"]
  detail = detail.join(" ")
  suffix = index == awards.length - 1 ? "" : "\\vspace{0.5em}"
  award_lines << "#{detail_label} \\quad\\enskip #{detail} \\\\#{suffix}"
end
award_lines << "     & \\\\"
write_section("awards_honors", award_lines)

focus = research_focus.fetch("summary")
focus_tex = tex(focus)
%w[systems networks security].each do |term|
  focus_tex.sub!(term, "\\textcolor{blue}{#{term}}")
end
write_section("research_focus", [
  "  \\shortstack[l]{\\Large{Research}\\\\\\Large{Focus}} & #{focus_tex}\\\\",
  "                & \\\\\\vspace{0.5em}"
])

impact_lines = []
research_impact.each_with_index do |impact, index|
  label = index.zero? ? "  \\Large{Research} &" : index == 1 ? "  \\Large{Impact} &" : "     &"
  # Suppress the generated file's final end-of-line space so LaTeX does not
  # start an empty tabular row before the surrounding \end{tabular}.
  suffix = index == research_impact.length - 1 ? " \\\\%" : "\\\\ \\vspace{0.5em}"
  impact_lines << "#{label} [#{impact['year']}] #{markdown_to_tex(impact.fetch('description'))}#{suffix}"
end
write_section("research_impact", impact_lines)

talk_lines = []
invited_talks.each_with_index do |talk, talk_index|
  title_label = talk_index.zero? ? " \\Large{Invited} &" : "     &"
  talk_lines << "#{title_label} \\textcolor{teal}{#{tex(talk['title'])}}\\\\"
  talk["appearances"].each_with_index do |appearance, appearance_index|
    event_label = talk_index.zero? && appearance_index.zero? ? " \\Large{Talks}   &" : "     &"
    event = "#{tex(appearance['venue'])}, #{tex(appearance['date'])}"
    event += " \\textcolor{blue}{(#{tex(appearance['note'])})}" if appearance["note"]
    last_appearance = appearance_index == talk["appearances"].length - 1
    last_talk = talk_index == invited_talks.length - 1
    suffix = last_appearance && !last_talk ? "\\\\\\vspace{0.5em}" : "\\\\"
    talk_lines << "#{event_label} \\quad\\enskip \\textit{#{event}}#{suffix}"
  end
end
talk_lines << "     & \\\\"
write_section("invited_talks", talk_lines)

funding_lines = []
funding.each_with_index do |grant, index|
  if index == 6
    funding_lines.concat([
      "\\end{tabular}",
      "}",
      "",
      "{\\normalsize",
      "\\noindent \\begin{tabular}{@{} l l}"
    ])
  end
  label = if index.zero?
            "     \\Large{Funding} &"
          elsif index == 6
            "     \\Large{\\textcolor{white}{Funding}}&"
          else
            "     &"
          end
  title = [grant["source"], grant["project"]].compact.join(": ")
  funding_lines << "#{label} \\textcolor{teal}{#{tex(title)}} \\\\\\vspace{0.5em}"
  detail = "#{tex(grant['period'])}, #{tex(grant['amount'])}"
  clauses = []
  if grant["principal_investigator"]
    principal = tex(grant["principal_investigator"])
    principal = "\\textbf{#{principal}}" if grant["principal_investigator"] == profile["name"]
    clauses << "PI: #{principal}"
  end
  if grant["co_investigators"]
    investigators = grant["co_investigators"].map do |name|
      rendered = tex(name)
      name == profile["name"] ? "\\textbf{#{rendered}}" : rendered
    end
    investigator_label = investigators.length == 1 ? "Co-PI" : "Co-PIs"
    clauses << "#{investigator_label}: #{investigators.join(', ')}"
  end
  clauses << tex(grant["note"]) if grant["note"]
  if grant["allocation"]
    allocation = tex(grant["allocation"])
    surname = tex(profile["name"].split.last)
    allocation.sub!(surname, "\\textbf{#{surname}}")
    clauses << allocation
  end
  detail += "; #{clauses.join(', ')}" unless clauses.empty?
  funding_lines << "     & \\quad\\enskip #{detail} \\\\"
end
funding_lines << "     & \\\\"
write_section("funding", funding_lines)

teaching_lines = []
groups = teaching.flat_map do |course|
  course["offerings"].group_by { |offering| offering["number"] || course["number"] }.map do |number, offerings|
    [course["name"], number, offerings]
  end
end
groups.each_with_index do |(name, number, offerings), group_index|
  label = group_index.zero? ? "     \\Large{Teaching} &" : "     &"
  teaching_lines << "#{label} \\textcolor{teal}{#{tex(number)}: #{tex(name)}}\\\\"
  offerings.each_with_index do |offering, index|
    suffix = index == 1 && offerings.length > 2 ? "\\vspace{0.5em}" : ""
    teaching_lines << "     & \\quad\\enskip #{tex(offering['term'])}: #{tex(offering['role'])}, #{offering['lectures']} Lectures, Enrollment: #{offering['enrollment']} (YC)\\\\#{suffix}"
  end
end
teaching_lines << "     & \\\\"
write_section("teaching", teaching_lines)

advising_lines = ["     \\Large{Advising} & \\textcolor{teal}{Postdoctoral Research:} \\\\\\vspace{0.5em}"]
advising["postdocs"].each do |person|
  detail = "#{tex(person['name'])} (#{person['start']}$-$"
  detail += ", co-advised with #{tex(person['coadvisor'])}" if person["coadvisor"]
  advising_lines << "     & #{detail})\\\\"
end
advising_lines << "     & \\textcolor{teal}{Graduate Student Research:}\\\\"
advising["phd"].each_with_index do |person, index|
  detail = tex(person["name"])
  dates = period(person)
  if dates
    detail += " (#{tex_period(dates)}, PhD)"
  else
    detail += " (PhD)"
  end
  detail += " (\\textcolor{blue}{$\\rightarrow$ #{tex(person['destination'])}})" if person["destination"]
  suffix = index == advising["phd"].length - 1 ? "\\vspace{0.5em}" : ""
  advising_lines << "     & #{detail}\\\\#{suffix}"
end
advising["masters"].each do |person|
  dates = period(person)
  detail = "#{tex(person['name'])} (#{dates ? "#{tex_period(dates)}, " : ''}Masters)"
  detail += " (\\textcolor{blue}{$\\rightarrow$ #{tex(person['destination'])}})" if person["destination"]
  advising_lines << "     & #{detail}\\\\"
end
undergraduates = advising["undergraduates"].map do |person|
  item = tex(person["name"])
  item += " (#{tex_period(person['period'])})" if person["period"]
  item += " (\\textcolor{blue}{$\\rightarrow$ #{tex(person['destination'])}})" if person["destination"]
  estimated_length = person["name"].length + person.fetch("period", "").to_s.length + person.fetch("destination", "").length + 8
  [item, estimated_length]
end
chunks = undergraduates.each_with_object([]) do |item, lines|
  if lines.empty? || lines.last.sum { |entry| entry[1] } + item[1] > 90
    lines << [item]
  else
    lines.last << item
  end
end
chunks.each_with_index do |chunk, index|
  items = chunk.map(&:first)
  prefix = index.zero? ? "     & \\textcolor{teal}{Undergraduate Student Research:} " : "     & "
  advising_lines << "#{prefix}#{items.join(', ')}#{index < chunks.length - 1 ? ',' : ''}\\\\"
end
advising_lines << "     & \\\\"
write_section("advising", advising_lines)

outreach_lines = [
  " \\Large{Education} & \\textcolor{teal}{#{tex(education_outreach['program'])}}\\\\",
  " \\Large{Outreach} & \\quad\\enskip \\textit{``#{tex(education_outreach['workshop'])}''}\\\\"
]
education_outreach["activities"].each do |activity|
  outreach_lines << "     & \\quad\\enskip #{tex(activity)}\\\\"
end
write_section("education_outreach", outreach_lines)

community_lines = []
organization = community_service["organization"].first
community_lines << " \\Large{Community} & \\textcolor{teal}{Organization Committee:} \\href{#{organization['url']}}{#{organization['venue']}'#{organization['year'].to_s[-2, 2]} #{tex(organization['role'])}}\\\\"
committees = community_service["program_committees"].sort_by { |item| item["year"] }
formatted = committees.map { |item| item["url"] ? "\\href{#{item['url']}}{#{item['venue']} #{item['year']}}" : "#{item['venue']} #{item['year']}" }
formatted.each_slice(5).with_index do |items, index|
  label = index.zero? ? " \\Large{Service}   & \\textcolor{teal}{Program Committee:} " : "     & "
  trailing = index == (formatted.length - 1) / 5 ? "" : ","
  community_lines << "#{label}#{items.join(', ')}#{trailing}\\\\ "
end
editorial = community_service["editorial"].first
community_lines << "     & \\textcolor{teal}{Journal #{tex(editorial['role'])}:} \\href{#{editorial['url']}}{#{editorial['venue']} #{editorial['year']}} \\\\"
external = community_service["external_program_committees"].first
community_lines << "     & \\textcolor{teal}{External Program Committee:} \\href{#{external['url']}}{#{external['venue']} #{external['year']}} \\\\"
panel = community_service["panels"].first
community_lines << "     & \\textcolor{teal}{#{tex(panel['sponsor'])} Panels:} #{tex(panel['note'])}\\\\"
community_lines << "     & \\\\"
write_section("community_service", community_lines)

university_lines = []
university_service.each_with_index do |item, index|
  label = index.zero? ? " \\Large{University} &" : " \\Large{Service}   &"
  university_lines << "#{label}  \\textcolor{teal}{#{tex(item['role'])}:} #{item['periods'].map { |value| tex(value) }.join(', ')} \\\\"
end
university_lines << "     & \\\\"
write_section("university_service", university_lines)

department_lines = []
department_service.each_with_index do |item, index|
  label = index.zero? ? " \\Large{Department} &" : index == 1 ? " \\Large{Service}   &" : "     &"
  if item["members"]
    first_members = item["members"].first(4).join(", ")
    department_lines << "#{label} \\textcolor{teal}{#{tex(item['role'])}:} #{tex(first_members)},\\\\"
    department_lines << "     & #{tex(item['members'].drop(4).join(', '))}\\\\"
  else
    department_lines << "#{label}  \\textcolor{teal}{#{tex(item['role'])}:} #{tex(item['detail'])} \\\\"
  end
end
department_lines << "     & \\\\"
write_section("department_service", department_lines)
