#!/usr/bin/env ruby

require "fileutils"
require "yaml"

ROOT = File.expand_path("..", __dir__)
DATA = File.join(ROOT, "_data")
OUTPUT = File.join(ROOT, "cv", "generated")

def load_data(name)
  YAML.safe_load_file(File.join(DATA, "#{name}.yml"), aliases: true)
end

def tex(value)
  replacements = {
    "\\" => "\\textbackslash{}",
    "&" => "\\&",
    "%" => "\\%",
    "$" => "\\$",
    "#" => "\\#",
    "_" => "\\_",
    "{" => "\\{",
    "}" => "\\}"
  }
  value.to_s.gsub(/[\\&%$#_{}]/) { |character| replacements.fetch(character) }
end

# Date range with an en dash and full years: "2025-28" -> "2025--2028",
# "2026 - Present" -> "2026--present", open-ended "2022-" -> "2022--present".
def tex_period(value)
  text = value.to_s.strip
  text = text.sub(/\A(\d{4})\s*-\s*(\d{2})\z/) { "#{$1}-#{$1[0, 2]}#{$2}" }
  text = text.sub(/-\s*\z/, "-present").sub(/present\z/i, "present")
  tex(text).gsub(/\s*-\s*/, "--")
end

# Normalize year ranges embedded in free text (e.g. "Created ... (2021-25)").
def tex_with_periods(value)
  tex(value).gsub(/\b(\d{4})-(\d{2}|\d{4})\b/) do
    "#{$1}--#{$2.length == 2 ? $1[0, 2] + $2 : $2}"
  end
end

def period(person)
  return person["period"] if person["period"]
  return nil unless person["start"] || person["end"]

  "#{person['start']}-#{person['end']}"
end

MONTH_ABBREVIATIONS = %w[January February March April May June July August September October November December]
  .to_h { |month| [month, month[0, 3]] }

def short_date(value)
  value.to_s.sub(/\A(#{MONTH_ABBREVIATIONS.keys.join('|')})\b/) { MONTH_ABBREVIATIONS[$1] }
end

# Site-relative links (e.g. /papers/mind/) only resolve on the website, so the
# PDF needs them absolute.
def absolute_link(target)
  target.start_with?("/") ? load_data("profile").fetch("website").chomp("/") + target : target
end

def markdown_to_tex(value)
  result = +""
  cursor = 0
  value.to_enum(:scan, /\[([^\]]+)\]\(([^)]+)\)/).each do
    match = Regexp.last_match
    result << tex(value[cursor...match.begin(0)])
    result << "\\href{#{absolute_link(match[2])}}{#{tex(match[1])}}"
    cursor = match.end(0)
  end
  result << tex(value[cursor..])
  result
end

# Row terminator: rows that close a group get extra space below them; rows
# marked keep_with_next never end a page.
def row_end(gap, keep_with_next: false)
  terminator = keep_with_next ? "\\\\*" : "\\\\"
  gap ? "#{terminator}\\noalign{\\vskip 0.5em}" : terminator
end

# Bib entries as { key => { type:, title: } }, for matching award titles to
# publications. Only reads the shared bibliography; never writes it.
def bib_entries
  text = File.read(File.join(ROOT, "_bibliography", "papers.bib"))
  text.scan(/@(\w+)\s*\{\s*([^,\s]+)\s*,(.*?)\n\}/m).to_h do |type, key, body|
    title = body[/^\s*title\s*=\s*\{+([^{}]+)\}+/, 1]
    [key, { type: type.downcase, title: title }]
  end
end

def normalize_title(value)
  value.to_s.downcase.gsub(/[^a-z0-9]/, "")
end

# Keys of publications listed in the CV (\cvpub{key}); cross-references are
# only emitted for these so LaTeX never prints "??".
def cv_publication_keys
  File.read(File.join(ROOT, "cv", "src", "cv.tex")).scan(/\\cvpub\{([^}]+)\}/).flatten
end

def write_section(name, lines)
  File.write(
    File.join(OUTPUT, "#{name}.tex"),
    (["% Generated by scripts/generate_cv.rb. Do not edit."] + lines).join("\n") + "\n"
  )
end

profile = load_data("profile")
education = load_data("education")
work_history = load_data("work_history")
awards = load_data("awards_honors")
research_focus = load_data("research_focus")
research_impact = load_data("research_impact")
invited_talks = load_data("invited_talks")
funding = load_data("funding")
teaching = load_data("teaching")
advising = load_data("advising")
education_outreach = load_data("education_outreach")
community_service = load_data("community_service")
university_service = load_data("university_service")
department_service = load_data("department_service")

FileUtils.mkdir_p(OUTPUT)
Dir.glob(File.join(OUTPUT, "*.tex")).each { |path| FileUtils.rm_f(path) }

department = profile["department"].to_s.sub(/\ADepartment of /, "")
position_line = department.empty? ? "#{profile['title']}, #{profile['institution']}" :
  "#{profile['title']} of #{department}, #{profile['institution']}"
profile_links = ["\\href{mailto:#{profile['email']}}{#{tex(profile['email'])}}",
                 "\\href{#{profile['website']}}{\\cvwebsitelabel}"]
{ "scholar" => "Google Scholar", "dblp" => "DBLP", "orcid" => "ORCID" }.each do |field, name|
  profile_links << "\\href{#{profile[field]}}{#{name}}" if profile[field]
end

File.write(File.join(OUTPUT, "profile.tex"), <<~TEX)
  % Generated by scripts/generate_cv.rb. Do not edit.
  \\newcommand{\\cvname}{#{tex(profile['name'])}}
  \\newcommand{\\cvtitle}{#{tex(profile['title'])}}
  \\newcommand{\\cvinstitution}{#{tex(profile['institution'])}}
  \\newcommand{\\cvemail}{#{tex(profile['email'])}}
  \\newcommand{\\cvwebsite}{#{profile['website']}}
  \\newcommand{\\cvwebsitelabel}{#{tex(profile['website'].sub(%r{\Ahttps?://(www\.)?}, '').chomp('/'))}}
  \\newcommand{\\cvposition}{#{tex(position_line)}}
  \\newcommand{\\cvprofilelinks}{#{profile_links.join('\\hspace{0.8em}\\textbullet\\hspace{0.8em}')}}
TEX

# Register the CV owner and advisees (by given/family name) so the
# bibliography can bold the owner and mark advisees in author lists. A "*"
# variant covers equal-contribution markers in the bib.
def name_variants(full_name)
  parts = full_name.split
  given = parts[0...-1].join(" ")
  family = parts.last
  [[given, family], [given, "#{family}*"]]
end

advisee_names = %w[postdocs phd masters undergraduates].flat_map { |group| advising.fetch(group, []) }
  .map { |person| person["name"] }.uniq
advisee_lines = name_variants(profile["name"]).map { |given, family| "\\cvself{#{given}}{#{family}}" }
advisee_names.each do |name|
  name_variants(name).each { |given, family| advisee_lines << "\\cvadvisee{#{given}}{#{family}}" }
end
write_section("advisees", advisee_lines)

education_lines = []
education.each_with_index do |entry, index|
  label = index.zero? ? " \\cvlabel{Education} &" : "     &"
  education_lines << "#{label} \\textbf{#{tex(entry['institution'])}} \\\\*"
  details = "\\textit{#{tex(entry['degree'])} (#{tex_period("#{entry['start']}-#{entry['end']}")})}"
  details += ", \\textit{Advised by #{tex(entry['advisor'])}}" if entry["advisor"]
  education_lines << "     & \\cvsub #{details} #{row_end(index < education.length - 1)}"
end
education_lines << "     & \\\\"
write_section("education", education_lines)

work_lines = []
work_history.each_with_index do |entry, index|
  label = index.zero? ? " \\cvlabel{Work\\\\History} &" : "     &"
  work_lines << "#{label} \\textbf{#{tex(entry['institution'])}#{entry['unit'] ? ", #{tex(entry['unit'])}" : ''}}\\\\*"
  entry["positions"].each_with_index do |position, position_index|
    range = position["period"] ? tex(position["period"]) : tex_period("#{position['start']}-#{position['end']}")
    gap = position_index == entry["positions"].length - 1 && index < work_history.length - 1
    work_lines << "     & \\cvsub \\textit{#{tex(position['title'])}, #{range}}#{row_end(gap)}"
  end
end
work_lines << "     & \\\\"
write_section("work_history", work_lines)

# Awards for a paper in the CV fit on one line: the award, the paper's short
# name, and its number (e.g. [C4]). Other awards keep a detail line.
publications = bib_entries
listed_keys = cv_publication_keys
# Match on the full title, falling back to the short name before the colon
# (award and bib titles sometimes differ slightly in wording).
short_title = ->(title) { title.to_s.include?(":") ? title.split(":").first : nil }
award_publication = lambda do |work|
  listed = publications.select { |key, _entry| listed_keys.include?(key) }
  matches = listed.select { |_key, entry| normalize_title(entry[:title]) == normalize_title(work) }
  if matches.empty? && short_title.call(work)
    matches = listed.select do |_key, entry|
      short_title.call(entry[:title]) && normalize_title(short_title.call(entry[:title])) == normalize_title(short_title.call(work))
    end
  end
  matches.min_by { |_key, entry| entry[:type] == "inproceedings" ? 0 : 1 }&.first
end

award_lines = []
awards.each_with_index do |award, index|
  label = index.zero? ? " \\cvlabel{Awards \\&\\\\Honors} &" : "     &"
  gap = index < awards.length - 1
  # cv_name/cv_description are CV-only overrides that keep the award on one line.
  award_name = award["cv_name"] || award["name"]
  award_description = award["cv_description"] || award["description"]
  # A description that only introduces the paper (e.g. "For paper") is
  # redundant once the award links to it.
  lead_in = award["description"].to_s.strip.match?(/\AFor (the )?paper\z/i)
  key = award["work"] && (!award["description"] || lead_in) && award_publication.call(award["work"])
  if key
    short_name = award["work"].include?(":") ? award["work"].split(":").first : award["work"]
    award_lines << "#{label} \\textbf{#{tex(award_name)}} for \\emph{#{tex(short_name)}} \\ref{pub:#{key}}#{row_end(gap)}"
    next
  end
  # Other awards read as one sentence on the award's line: a description
  # starting with "For"/"To" continues it in lowercase ("... 2023 for
  # innovations in ..."); anything else follows a comma.
  detail = []
  if award_description
    description = tex_with_periods(award_description.strip.chomp("."))
    description = description.sub(/\A(For|To)\b/, &:downcase)
    detail << description
  end
  detail << "\\emph{#{tex(award['work'])}}" if award["work"]
  separator = detail.first.to_s.match?(/\A(for|to)\b/) ? " " : ", "
  text = detail.empty? ? "" : "#{separator}#{detail.join(' ')}"
  award_lines << "#{label} \\textbf{#{tex(award_name)}}#{text}#{row_end(gap)}"
end
award_lines << "     & \\\\"
write_section("awards_honors", award_lines)

focus = research_focus.fetch("summary")
focus_tex = tex(focus)
%w[systems networks security].each do |term|
  focus_tex.sub!(term, "\\emph{#{term}}")
end
write_section("research_focus", [
  "  \\cvlabel{Research\\\\Focus} & #{focus_tex}\\\\",
  "     & \\\\"
])

impact_lines = []
research_impact.each_with_index do |impact, index|
  label = index.zero? ? "  \\cvlabel{Research\\\\Impact} &" : "     &"
  impact_lines << "#{label} [#{impact['year']}] #{markdown_to_tex(impact.fetch('description'))}#{row_end(index < research_impact.length - 1)}"
end
impact_lines << "     & \\\\"
write_section("research_impact", impact_lines)

talk_lines = []
invited_talks.each_with_index do |talk, talk_index|
  title_label = talk_index.zero? ? " \\cvlabel{Invited\\\\Talks} &" : "     &"
  talk_lines << "#{title_label} \\cventry{#{tex(talk['title'])}}\\\\*"
  # All appearances of a talk share one wrapped line; venues may contain
  # commas, so appearances are separated by semicolons.
  appearances = talk["appearances"].map do |appearance|
    context = [short_date(appearance["date"]), appearance["note"]&.sub(/\.\z/, "")&.sub(/\A./, &:downcase)].compact
    "#{tex(appearance['venue'])} (#{context.map { |item| tex(item) }.join('; ')})"
  end
  talk_lines << "     & \\cvsub #{appearances.join('; ')}#{row_end(talk_index < invited_talks.length - 1)}"
end
talk_lines << "     & \\\\"
write_section("invited_talks", talk_lines)

funding_lines = []
funding.each_with_index do |grant, index|
  label = index.zero? ? "     \\cvlabel{Funding} &" : "     &"
  title = [grant["source"], grant["project"]].compact.join(": ")
  funding_lines << "#{label} \\cventry{#{tex(title)}} \\\\*"
  detail = "#{tex_period(grant['period'])}, #{tex(grant['amount'])}"
  clauses = []
  if grant["principal_investigator"]
    principal = tex(grant["principal_investigator"])
    principal = "\\textbf{#{principal}}" if grant["principal_investigator"] == profile["name"]
    clauses << "PI: #{principal}"
  end
  if grant["co_investigators"]
    investigators = grant["co_investigators"].map do |name|
      rendered = tex(name)
      name == profile["name"] ? "\\textbf{#{rendered}}" : rendered
    end
    investigator_label = investigators.length == 1 ? "Co-PI" : "Co-PIs"
    clauses << "#{investigator_label}: #{investigators.join(', ')}"
  end
  clauses << tex(grant["note"]) if grant["note"]
  if grant["allocation"]
    allocation = tex(grant["allocation"])
    surname = tex(profile["name"].split.last)
    allocation.sub!(surname, "\\textbf{#{surname}}")
    clauses << allocation
  end
  detail += "; #{clauses.join(', ')}" unless clauses.empty?
  funding_lines << "     & \\cvsub #{detail} #{row_end(index < funding.length - 1)}"
end
funding_lines << "     & \\\\"
write_section("funding", funding_lines)

teaching_lines = []
groups = teaching.flat_map do |course|
  course["offerings"].group_by { |offering| offering["number"] || course["number"] }.map do |number, offerings|
    [course["name"], number, offerings]
  end
end
# State a role shared by every offering once, instead of on every line.
roles = teaching.flat_map { |course| course["offerings"].map { |offering| offering["role"] } }.uniq
shared_role = roles.length == 1 ? roles.first : nil
if shared_role
  teaching_lines << "     \\cvlabel{Teaching} & \\textit{#{tex(shared_role)} for all offerings below; YC enrollment in parentheses.}#{row_end(true, keep_with_next: true)}"
end
groups.each_with_index do |(name, number, offerings), group_index|
  label = group_index.zero? && !shared_role ? "     \\cvlabel{Teaching} &" : "     &"
  lectures = offerings.map { |offering| offering["lectures"] }.uniq
  per_term = lectures.length == 1 ? " (#{lectures.first} lectures per term)" : ""
  teaching_lines << "#{label} \\cventry{#{tex(number)}: #{tex(name)}}#{per_term}\\\\*"
  terms = offerings.map do |offering|
    context = [offering["enrollment"]]
    context.unshift(tex(offering["role"])) unless shared_role
    context << "#{offering['lectures']} lectures" if per_term.empty?
    "#{tex(offering['term'])} (#{context.join(', ')})"
  end
  teaching_lines << "     & \\cvsub #{terms.join(', ')}#{row_end(group_index < groups.length - 1)}"
end
teaching_lines << "     & \\\\"
write_section("teaching", teaching_lines)

def advisee(name, dates, destination, note = nil)
  context = [dates && tex_period(dates), note].compact.join(", ")
  item = tex(name)
  item += " (#{context})" unless context.empty?
  item += " $\\rightarrow$ #{tex(destination)}" if destination
  item
end

# Advisees grouped by stage; PhD students split into current and graduated
# (an end year means graduated). Each group is a heading row plus one row per
# person, with a gap after the group.
current_phd, graduated_phd = advising["phd"].partition { |person| person["end"].nil? }
advising_groups = [
  ["Postdoctoral Researchers", advising["postdocs"].map do |person|
    advisee(person["name"], "#{person['start']}-", nil, person["coadvisor"] && "co-advised with #{tex(person['coadvisor'])}")
  end],
  ["Current PhD Students", current_phd.map { |person| advisee(person["name"], period(person), person["destination"]) }],
  ["Graduated PhD Students", graduated_phd.map { |person| advisee(person["name"], period(person), person["destination"]) }],
  ["Masters Students", advising["masters"].map { |person| advisee(person["name"], period(person), person["destination"]) }]
].reject { |_heading, items| items.empty? }

advising_lines = []
advising_groups.each_with_index do |(heading, items), group_index|
  label = group_index.zero? ? "     \\cvlabel{Advising} &" : "     &"
  advising_lines << "#{label} \\cventry{#{heading}}\\\\*"
  items.each_with_index do |item, index|
    advising_lines << "     & \\cvsub #{item}#{row_end(index == items.length - 1)}"
  end
end
undergraduates = advising["undergraduates"].map do |person|
  advisee(person["name"], person["period"], person["destination"])
end
advising_lines << "     & \\cventry{Undergraduate Researchers}\\\\*"
advising_lines << "     & \\cvsub #{undergraduates.join(', ')}\\\\"
advising_lines << "     & \\\\"
write_section("advising", advising_lines)

outreach_lines = [
  " \\cvlabel{Education\\\\Outreach} & \\cventry{#{tex(education_outreach['program'])}}\\\\",
  "     & \\cvsub \\textit{``#{tex(education_outreach['workshop'])}''}\\\\"
]
education_outreach["activities"].each do |activity|
  outreach_lines << "     & \\cvsub #{tex(activity)}\\\\"
end
outreach_lines << "     & \\\\"
write_section("education_outreach", outreach_lines)

community_lines = []
organization = community_service["organization"].first
community_lines << " \\cvlabel{Community\\\\Service} & \\cventry{Organization Committee:} \\href{#{organization['url']}}{\\cvplain{#{organization['venue']}'#{organization['year'].to_s[-2, 2]} #{tex(organization['role'])}}}\\\\"
committees = community_service["program_committees"].sort_by { |item| item["year"] }
formatted = committees.map { |item| item["url"] ? "\\href{#{item['url']}}{\\cvplain{#{item['venue']} #{item['year']}}}" : "#{item['venue']} #{item['year']}" }
community_lines << "     & \\cventry{Program Committee:} #{formatted.join(', ')}\\\\"
editorial = community_service["editorial"].first
community_lines << "     & \\cventry{Journal #{tex(editorial['role'])}:} \\href{#{editorial['url']}}{\\cvplain{#{editorial['venue']} #{editorial['year']}}} \\\\"
external = community_service["external_program_committees"].first
community_lines << "     & \\cventry{External Program Committee:} \\href{#{external['url']}}{\\cvplain{#{external['venue']} #{external['year']}}} \\\\"
panel = community_service["panels"].first
community_lines << "     & \\cventry{#{tex(panel['sponsor'])} Panels:} #{tex(panel['note'])}\\\\"
community_lines << "     & \\\\"
write_section("community_service", community_lines)

university_lines = []
university_service.each_with_index do |item, index|
  label = index.zero? ? " \\cvlabel{University\\\\Service} &" : "     &"
  university_lines << "#{label} \\cventry{#{tex(item['role'])}:} #{item['periods'].map { |value| tex_period(value) }.join(', ')} \\\\"
end
university_lines << "     & \\\\"
write_section("university_service", university_lines)

department_lines = []
department_service.each_with_index do |item, index|
  label = index.zero? ? " \\cvlabel{Department\\\\Service} &" : "     &"
  detail = item["members"] ? tex(item["members"].join(", ")) : tex_with_periods(item["detail"])
  department_lines << "#{label} \\cventry{#{tex(item['role'])}:} #{detail} \\\\"
end
write_section("department_service", department_lines)
